### ISSUE TITLE
docker install failure

### ISSUE THREAD

**Issue by Yue-You** [HumanCompatibleAI/adversarial-policies#44]
Hello,

We're trying to reproduce the paper and when running the command `$ docker build .`, this error message showed up:

`COPY failed: stat /var/lib/docker/tmp/docker-builder836225598/adversarial-policies/ci/build_venv.sh: no such file or directory`

We tried it on different operating systems (Mac OS and Linux) and we all have this same error. Could you help us with this issue?

**Comment by AdamGleave** [comment]
Thanks for the bug report, looks like a typo introduced in https://github.com/HumanCompatibleAI/adversarial-policies/pull/43, should be fixed in `master`. Closing for now, please re-open if the issue persists.

**Comment by Yue-You** [comment]
Thank you Adam, it works now!
