### ISSUE TITLE
Policy Evaluation question

### ISSUE THREAD

**Issue by BradAlt** [HumanCompatibleAI/adversarial-policies#50]
Both recommendations from the README,
>experiments/modelfree/baselines.sh

and
> experiments/modelfree/attack_transfer.sh data/aws-public/multi_train/paper/20190429_011349

https://hastebin.com/raw/nivikiwima
and
https://hastebin.com/raw/ojebamoqaq
respectively

Seem to be attempting to evaluate, but then end in `ValueError: Unrecognized config type '['`
They create folders in ~/adversarial-policies/data/aws/score_agents/adversary_masked_init but then dont fill them with anything.

Am I doing something wrong? I assumed Sacred is configured with the given scripts because I have not interacted with it. I have already imported `aws-public`

Really dig the outcome of the paper btw.  Using pure RL and MDPs to adversarially attack a black-box victim is very cool. YSNP ZooVD1 vs AdvD1 is an interesting case where Adv is still twitching to do the adversarial attack, but cant rely on it solely anymore. Great animations. Found the paper through 2 Minute Papers on Youtube and decided to do a school project recreating the results. Got most of the way there but I cant seem to get this final step of picking and choosing policys to put against eachother.

Any help would be appreciated

**Comment by AdamGleave** [comment]
Thanks for the bug report. Looks like Sacred is interpreting the lists as a string. I've added double quotes around the list entries in https://github.com/HumanCompatibleAI/adversarial-policies/commit/ea16b14ad5b7072c356bc6462720300ee48696d9 and this seems to fix it. Feel free to reopen if you still have issues.
