### ISSUE TITLE
Which version of gym-compete should I use?

### ISSUE THREAD

**Issue by AndssY** [HumanCompatibleAI/adversarial-policies#59]
Hello Gleave,

We are trying to reproduce the paper but meeting some problem when evaluating, the results are not same with paper. When using baselines vs random policy in Sumo humans, it usually tie, not win. 

I notice the winning condition is modified, this may means my gym-compete version is not true.

I try to git clone this version `git clone https://github.com/HumanCompatibleAI/multiagent-competition.git@3a3f9dc` but meet this error `fatal: unable to access 'https://github.com/HumanCompatibleAI/multiagent-competition.git@3a3f9dc/': The requested URL returned error: 400`

This url cannot be accessed. How can I get the right gym-compete?

Thanks a lot!

**Comment by AdamGleave** [comment]
The repo https://github.com/HumanCompatibleAI/multiagent-competition is accessible. I think you just need to `git clone https://github.com/HumanCompatibleAI/multiagent-competition` then `git checkout 3a3f9dc`. `pip install requirements.txt` should handle this for you though.
